// import { Inter } from "next/font/google";
import "./globals.css";
import React from "react";
import Contact from "../components/contact/page";
import Footer from "../components/footer/page";
import NavBar from "@/components/navbar/page";

export const metadata = {
  title: "Cleaning",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="relative">
        <Contact />
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
